comment_id = "9bb1c900-5bff-11eb-9f72-053de2e9169d"
slug = "hack-for-ios-safari-to-display-html-video-thumbnail"
name = "Sage"
email = "b5a4ad51286c0e6b46cf36e287495798"
message = "Thanks! ğŸ‘"
date = "2021-01-21T15:44:55.367Z"
